name: safe_guardian
description: "시니어를 위한 능동형 스미싱/피싱 방어 앱 - 안심지킴이"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD
=======
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
>>>>>>> 6ddcc6c101a73da16c16f46604675fd4ca04a30c
  assets:
    - assets/images/
